fixtures:
  repositories:
    "concat":   "git://github.com/puppetlabs/puppetlabs-concat.git"
    "epel":     "git://github.com/stahnma/puppet-module-epel.git"
    "monitor":  "git://github.com/example42/puppet-monitor.git"
    "puppi":    "git://github.com/example42/puppi.git"
    "stdlib":   "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "fail2ban": "#{source_dir}"
