fixtures:
  forge_modules:
    concat:
      repo: 'puppetlabs/concat'
      ref: '2.2.1'
    epel: 'stahnma/epel'
    monitor: 'example42/monitor'
    puppi: 'example42/puppi'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.13.0'
  symlinks:
    "fail2ban": "#{source_dir}"
