language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
branches:
  only:
  - master
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2
script: bundle exec rake test
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 3.6.0"
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.0.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
matrix:
  exclude:
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.8.0"
notifications:
  slack:
    rooms:
      secure: TeudCnIebISjwlinNK4oKhnCfJ1BZeXFfc+UedXnS0CmkSkTxQBY5nN3fwkcLTPKZZDCTTgDopyhYGC+uEdjA2c8a8gznn5UJVCX/qTVHuPgE0PSe7VwmiPJ8Mb6p0DYXijwbU9OaqRcDmluX05eXy22ksjWqNsTVfpxGG793V71d3pwUKJeEHA35+/ICVcU21F9dL+874CurzuIpB9ohzD2/nPQGkvLvQ43C1nejMiH2cP69JXPTsb6y1CAXU07qpQTsK031n6TvdtIrScS0KQkq6VU0NxUGEO7eY4hNBDctWDxFMOcVWvizEQPvgcm1tlP12Wwigc1lr4JHpatG1fr+cbHHp5nT4qWolk4Z6aKy5U0chuqdPYsesV2z7XeAXDnURIRIuasS2BPwMe5u7Hi9CVPuLq5x9LAZXl4jvfzzciIN7M2VfWaPxNL4ZOACHBYwOakSZK+o8nTI9D7Pvhy3tP+XsDFLpInhN+TaD06FNtVcxIJS1aHbe3kThjzHOxhd1mWAYmB4ODsUG/HudZydvXWmLxp1zOmIam6h9XQHt28hcdSv0OP+JIVdD0KDDZYv4PfGeD68WhP6D0nWfNm2e4mjP9GprApdOPe0F6sDDxc80xAYb9Er+eflKpUBTEZOsJoVW9rewSvuVV4M64ynxs5dI0vVC7jozuAs80=
