language: ruby
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/spec/fixtures/modules
before_install: rm Gemfile.lock || true
install:
  - bundle install --without development system_tests --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake spec_prep
branches:
  only:
  - master
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2
script: bundle exec rake test
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 3.6.0"
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.0.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
matrix:
  exclude:
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.8.0"
notifications:
  slack:
    rooms:
      secure: gmkvVso08W4aeShMCbi8BmUYDjdeAtjcgj4EHAWfsWfXKNx2I1MnLWf9cVDU1mLo8h6gdfJaD0ZF6Kz9i5Jy5eoaaS28TSEGsoZonQjv/zMwY3jTySRBrhA48iuvktN52EEQSGrQm4N1Ej+Zfwi8+w+2J66lux9pITaxslX4rTTRkLpv4ihF8UKCamWqM3vycO4DVLw0kGUyoQ9mg7iCl8T9lyAGALii7yCkEwSfSUxTLbmcImX4ImHMScG/BLppnBADMxpDkS9w1XszUn7T2lz5UabAvZKWQuH+7fcEcnvz2EEd+cOuu9ENdqRRzYjdnFcASrl4sJEGo7zBG6ZeIGosMLZHazXw6YHYWrvvU0NuGkzUT+GzV2DXB0UCA1z2//AV+XRdqTeV/0BSgzImtMo0nT65Gv5LFnTAjOSpLg5IlDdEfEZa7BsFb46relzRQQ1BUOu+63yz+i0VzBip9jvK8eIWTAf2ZE6P3S1l7FooYlVBQzMNyX2i8sLpOStK7PPi3kEUfmK8oZHA/pNbizJuXbfLiFgxDu0U4+bK3k/vVa/HmL7QvysifFR4AoUggN//43slptaWaLRLv9cRBFclWPpnTsqbF6t6xXN3mUo0O0tdJ+pIw+PviPQrbvzsoh1GkOQlelDl1fIQjD/t6UZcXygpgHSv1e1+ClJ5ft0=
