source 'https://rubygems.org'

puppetversion = ENV.key?('PUPPET_VERSION') ? "= #{ENV['PUPPET_VERSION']}" : ['>= 3.3']
gem 'facter', '>= 1.7.0'
gem 'hiera-eyaml'
gem 'librarian-puppet'
gem 'puppet', puppetversion
gem 'puppetlabs_spec_helper', '>= 0.1.0'
gem 'puppet-lint', '>= 0.3.2'
gem 'puppet-syntax'
gem 'rake'
gem 'requests'
gem 'rspec-puppet'
